---

- hosts: servers
  gather_facts: false
  remote_user: root
  tasks:
    - name: generate packstack answer file
      shell: |
        packstack \
          --gen-answer-file /root/packstack-answerfile.txt \
          \
          --os-glance-install=y \
          --os-cinder-install=n \
          --os-manila-install=n \
          --os-swift-install=n \
          --os-ceilometer-install=n \
          --os-sahara-install=n \
          --os-trove-install=n \
          --os-ironic-install=n \
          --os-neutron-lbaas-install=y \
          --provision-demo=n \
          --provision-tempest=n \
          \
          --keystone-admin-passwd=admin \
          --mariadb-pw=mariadb_password \
          \
          --os-neutron-ml2-type-drivers=vxlan,vlan,flat \
          --os-neutron-ml2-tenant-network-types=vlan,vxlan \
          --os-neutron-ml2-vlan-ranges=vlannet:{{ vlan_range }} \
          \
          --os-neutron-ovs-bridge-mappings=extnet:br-ex,vlannet:br-vlan \
          --os-neutron-ovs-bridge-interfaces=br-ex:em1,br-vlan:bond0 \
          --os-neutron-ovs-bridges-compute=br-ex,br-vlan \
          \
          --ntp-servers=0.pool.ntp.org,1.pool.ntp.org,2.pool.ntp.org \
          \
          --allinone

    - name: packstack install rdo pike
      shell: |
        packstack --debug --answer-file /root/packstack-answerfile.txt --timeout 600
      environment: "{{ proxy_env | default({}) }}"
    