---

- hosts: servers
  gather_facts: no
  remote_user: root
  vars:
    # proxy_env:
    #     http_proxy: http://10.250.64.99:3128
    #     https_proxy: http://10.250.64.99:3128
    #     HTTP_PROXY: http://10.250.64.99:3128
    #     HTTPS_PROXY: http://10.250.64.99:3128
  tasks:

  # install OS
  #   refer to IPMI installation guide

  # setup network
  #   vi /etc/sysconfig/network-scripts/ifcfg-em1
      # TYPE=Ethernet
      # PROXY_METHOD=none
      # BROWSER_ONLY=no
      # BOOTPROTO=static        dhcp -> static
      # DEFROUTE=yes
      # IPV4_FAILURE_FATAL=no
      # IPV6INIT=yes
      # IPV6_AUTOCONF=yes
      # IPV6_DEFROUTE=yes
      # IPV6_FAILURE_FATAL=no
      # IPV6_ADDR_GEN_MODE=stable-privacy
      # NAME=em1
      # UUID=d30d5277-7acd-41b2-b7e0-e3fd535d5e53
      # DEVICE=em1
      # ONBOOT=yes              no -> yes
      # IPADDR=10.250.11.111    -> added
      # NETMASK=255.255.255.0   -> added
      # GATEWAY=10.250.11.1     -> added
  #   systemctl restart network
  
  # reconfigure sshd
  #   vi /etc/ssh/sshd_config
      # PermitRootLogin yes
      # UseDNS no
      # PasswordAuthentication yes
  #   systemctl restart sshd

  # setup password-less
  #   ssh-copy-id root@10.250.11.111

    - name: check reachability
      ping:

    - name: update system configurations
      template:
        src: templates/{{ item[0] }}
        dest: "{{ item[1] }}"
      with_list:
        - ['bonding.conf.j2', '/etc/modprobe.d/bonding.conf']
        - ['ifcfg-bond0.j2', '/etc/sysconfig/network-scripts/ifcfg-bond0']
        - ['environment.j2', '/etc/environment']
        - ['resolv.conf.j2', '/etc/resolv.conf']
        - ['ifcfg-p3p1.j2', '/etc/sysconfig/network-scripts/ifcfg-p3p1']
        - ['ifcfg-p3p2.j2', '/etc/sysconfig/network-scripts/ifcfg-p3p2']
      loop_control:
        label: "{{ item[1] }}"

    - name: remote test interface bond0.*
      shell: rm -f /etc/sysconfig/network-scripts/ifcfg-bond0.*
      args:
        warn: no
    # why it doesn't work on with_fileglob - /etc/sysconfig/network-scripts/ifcfg-bond0.* ??!!
    # - name: remove test interfaces bond0.*
    #   file:
    #     state: absent
    #     path: "{{ item }}"
    #   with_fileglob:
    #     - /etc/sysconfig/network-scripts/ifcfg-bond0.*

    - name: set deltarpm=0 in /etc/yum.conf
      blockinfile:
        path: /etc/yum.conf
        block: deltarpm=0

    - name: verify yum packages installed
      yum:
        name:
          - vim
          - git
          - tree
          - curl
          - wget
          - tcpdump
          - yum-utils
          - screen
          - https://repos.fedorapeople.org/repos/openstack/EOL/openstack-pike/rdo-release-pike-1.noarch.rpm
        state: present
      environment: "{{ proxy_env | default({}) }}"

    - name: configure openstack-pike.baseurl
      shell: |
        yum-config-manager --quiet --save --setopt=openstack-pike.baseurl=http://vault.centos.org/7.6.1810/cloud/x86_64/openstack-pike/
    
    # use command 'yum --enablerepo=openstack-pike clean metadata' to clean metadata if this step always fails
    - name: install openstack packstack and dependencies
      yum:
        name:
          - openstack-packstack
          - python-pip
          - qemu-kvm
          - libvirt
          - libvirt-client
          - virt-install
        state: present
      environment: "{{ proxy_env | default({}) }}"

    - name: stop useless services
      systemd:
        state: stopped
        name: "{{ item }}"
      with_items:
        - firewalld
        - NetworkManager

    - name: start necessary services
      systemd:
        state: restarted
        name: "{{ item }}"
      with_items:
        - network
        - libvirtd
        